apiVersion: v1
data:
  01.config-map-nginx-config.conf: "server {\n   \tlisten\t\t\t80;\n   \tlisten\t\t\t443
    ssl;\n   \tserver_name  \t\twww.star-lord.com;\n\t\n\tssl_certificate\t\tcerts/06.https.cert;\n\tssl_certificate_key\tcerts/05.https.key;\n\tssl_protocols\t\tTLSv1
    TLSv1.1 TLSv1.2;\n\tssl_ciphers\t\tHIGH:!aNULL:!MD5;\n\t\n\tlocation / {\n\t\troot\t\t/usr/share/nginx/html;\n\t\tindex\t\tindex.html
    index.htm;\n\t}\n}\n"
  02.config-map-sleep-interval: |
    25
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cmap
