---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: secret-cmap
  name: secret-cmap
spec:
  replicas: 1
  selector:
    matchLabels:
      run: secret-cmap
  template:
    metadata:
      labels:
        run: secret-cmap
    spec:
      containers:
      - image: nginx:alpine
        name: web-server
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certs
          mountPath: /etc/nginx/certs
          readOnly: true
        ports:
        - containerPort: 80
        - containerPort: 443
      - image: luksa/fortune
        name: html-generator
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: html
          mountPath: /var/htdocs
      volumes:
      - name: html
        emptyDir: {}
      - name: config
        configMap:
          name: cmap
          items:
          - key: 01.config-map-nginx-config.conf
            path: https.conf 
      - name: certs
        secret:
          secretName: sec-ret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: secret-cmap-svc
  name: secret-cmap-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 80
  - port: 8443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    run: secret-cmap
