---
apiVersion: v1
kind: Pod
metadata:
  labels:
    key1: value1
  name: downward-pod
spec:
  containers:
  - image: busybox
    name: downward-container
    imagePullPolicy: IfNotPresent
    command: ["sleep", "999999"]
    resources:
      requests:
        cpu: 15m
        memory: 100Ki
      limits:
        cpu: 100m
        memory: 4Mi
    env:
    - name: POD_NAME
      valueFrom: 
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMEPSPACE
      valueFrom: 
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom: 
        fieldRef:
          fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom: 
        fieldRef:
          fieldPath: spec.nodeName
    - name: SERVICE_ACCOUNT
      valueFrom: 
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: CONTAINER_CPU_REQUESTS
      valueFrom: 
        resourceFieldRef:
          resource: requests.cpu
          divisor: 1m
    - name: CONTAINER_LIMITS_MEMORY
      valueFrom: 
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Ki
