---
apiVersion: v1
kind: Pod
metadata:
  labels:
    key1: value1
  name: downward-pod-vol
spec:
  containers:
  - image: busybox
    name: downward-container-vol
    imagePullPolicy: IfNotPresent
    command: ["sleep", "999999"]
    resources:
      requests:
        cpu: 15m
        memory: 100Ki
      limits:
        cpu: 100m
        memory: 4Mi
    volumeMounts:
    - name: downward-volume
      mountPath: /etc/downward
  volumes:
  - name: downward-volume
    downwardAPI:
      items:
      - path: "podName"
        fieldRef:
          fieldPath: metadata.name
      - path: "podNamespace" 
        fieldRef:
          fieldPath: metadata.namespace
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
      - path: "containerCPURequests"
        resourceFieldRef:
          containerName: downward-container-vol
          resource: requests.cpu
          divisor: 1m
      - path: "containerMemoryLimits"
        resourceFieldRef:
          containerName: downward-container-vol
          resource: limits.memory
          divisor: 1
