---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: volume-git
  name: volume-git
spec:
  replicas: 1
  selector:
    matchLabels:
      run: volume-git
  template:
    metadata:
      labels:
        run: volume-git
    spec:
      containers:
      - image: nginx
        name: web-server
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          #readOnly: true
      volumes:
      - name: html
        gitRepo:
          repository: https://github.com/sandeeplamb/kubetest.git
          revision: master
          directory: .
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: volume-git
  name: volume-git
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    run: volume-git
