---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: local-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: local-pvc-pod
  name: local-pvc-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      run: local-pvc-pod
  template:
    metadata:
      labels:
        run: local-pvc-pod
    spec:
      containers:
      - image: nginx
        name: web-server
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 80 
          protocol: TCP 
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          #readOnly: true
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: local-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: local-pvc-pod-svc
  name: local-pvc-pod-svc
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 80
  selector:
    run: local-pvc-pod
